// Code generated by MockGen. DO NOT EDIT.
// Source: pg_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/gabrielopesantos/myDrive-api/internal/models"
	gomock "github.com/golang/mock/gomock"
	v7 "github.com/minio/minio-go/v7"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// RecordFileInsertion mocks base method.
func (m *MockRepository) RecordFileInsertion(ctx context.Context, file *models.File) (*v7.UploadInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordFileInsertion", ctx, file)
	ret0, _ := ret[0].(*v7.UploadInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordFileInsertion indicates an expected call of RecordFileInsertion.
func (mr *MockRepositoryMockRecorder) RecordFileInsertion(ctx, file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFileInsertion", reflect.TypeOf((*MockRepository)(nil).RecordFileInsertion), ctx, file)
}
