version: "3.8"

services:
  postgresql:
    image: postgres:12-alpine
    container_name: postgresql_api
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./_data/postgres:/var/lib/postgresql/data
    networks:
      - web_api

  pgadminer4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    ports:
        - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - web_api

networks:
  web_api:
    driver: bridge
