version: "3.8"

services:
    redis:
      image: redis:6.2.4-alpine
      container_name: api_redis
      restart: always
      ports:
        - 6379:6379
      networks:
        - my_network

    postgresql:
      image: postgres:13.3-alpine
      container_name: postgesql
      ports:
        - 5432:5432
      restart: always
      environment:
        POSTGRES_USER: gabriel
        POSTGRES_PASSWORD: leirbag123
        POSTGRES_DB: users
      volumes:
        - ./pgdata/:/var/lib/postgresql/data
      networks:
        - my_network

    pgadminer4:
      container_name: pgadminer4
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: email@email.com
        PGADMIN_DEFAULT_PASSWORD: email
      ports:
        - 80:80 # IF TLS IS DISABLED ELSE 443
      networks:
        - my_network

    prometheus:
      container_name: prometheus_container
      image: prom/prometheus
      restart: always
      volumes:
        - ./docker/monitoring/prometheus-local.yml:/etc/prometheus/prometheus.yml:Z
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--storage.tsdb.retention=20d'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries/'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      ports:
        - 9090:9090
      networks:
        - my_network

    node_exporter:
      container_name: node_exporter_container
      image: prom/node-exporter
      restart: always
      ports:
        - 9101:9100
      networks:
        - my_network

    jaeger:
      container_name: jaeger_container
      image: jaegertracing/all-in-one:latest
      restart: always
      environment:
        - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      ports:
        - 5775:5775/udp
        - 6831:6831/udp
        - 6832:6832/udp
        - 5778:5778
        - 16686:16686
        - 14268:14268
        - 14250:14250
        - 9411:9411
      networks:
        - my_network

networks:
  my_network:
    driver: bridge
