version: "3.8"

services:
    postgresql:
      image: postgres:12-alpine
      container_name: api_postgesql
      ports:
        - 5432:5432
      restart: always
      environment:
        - POSTGRES_USER=gabriel
        - POSTGRES_PASSWORD=leirbag123
        - POSTGRES_DB=users
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      networks:
        - web_api

    pgadminer4:
      container_name: pgadminer4
      image: dpage/pgadmin4
      restart: always
      environment:
        - PGADMIN_DEFAULT_EMAIL=email@email.com
        - PGADMIN_DEFAULT_PASSWORD=email
      ports:
        - 80:80 # IF TLS IS DISABLED ELSE 443
      networks:
        - web_api

networks:
  web_api:
    driver: bridge
