version: "3.8"

services:
    redis:
      image: redis:6.2.4-alpine
      container_name: redis
      restart: always
      ports:
        - "6379:6379"

    redis-commander:
      container_name: redis-commander
      hostname: redis-commander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
        - REDIS_HOSTS=local:redis:6379:0
      ports:
        - "8081:8081"

    postgresql:
      image: postgres:13.3-alpine
      container_name: postgesql
      ports:
        - "5432:5432"
      restart: always
      environment:
        POSTGRES_USER: gabriel
        POSTGRES_PASSWORD: leirbag123
        POSTGRES_DB: users
      volumes:
        - ./pgdata/:/var/lib/postgresql/data

    pgadminer4:
      container_name: pgadminer4
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: email@email.com
        PGADMIN_DEFAULT_PASSWORD: email
      ports:
        - "80:80" # IF TLS IS DISABLED ELSE 443

    prometheus:
      container_name: prometheus_container
      image: prom/prometheus
      restart: always
      volumes:
        - ./docker/monitoring/prometheus-local.yml:/etc/prometheus/prometheus.yml:Z
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--storage.tsdb.retention=20d'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries/'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      ports:
        - "9090:9090"

    node_exporter:
      container_name: node_exporter_container
      image: prom/node-exporter
      restart: always
      ports:
        - "9101:9100"

    jaeger:
      container_name: jaeger_container
      image: jaegertracing/all-in-one:latest
      restart: always
      environment:
        - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
        - "16686:16686"
        - "14268:14268"
        - "14250:14250"
        - "9411:9411"
  
    minio:
      container_name: minio
      image: minio/minio
      restart: always
      ports:
        - "9000:9000"
        - "9001:9001"
      environment:
        - MINIO_ROOT_USER=gabriel
        - MINIO_ROOT_PASSWORD=leirbag123
      command: server /data --console-address ":9001"
