server:
  AppVersion: 1.0.0
  Port: :5000
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: secretkey
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false


cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true

session:
  Name: session-id
  Prefix: api-session
  Expire: 3600

logger:
  Development: true
  DisableCaller: false
  DisableStracktrace: false
  Encoding: console # json
  Level: info

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: gabriel
  PostgresqlPassword: leirbag123
  PostgresqlDbname: users
  PostgresqlSslmode: false

redis:
  RedisAddr: localhost:6379
  RedisPassword:
  RedisDB: 0
  RedisDefaultDB: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

metrics:
  Url: 0.0.0.0:7070
  ServiceName: api

jaeger:
  Host: localhost:6831
  ServiceName: REST_API
  LogSpans: false

minio:
  Endpoint: 127.0.0.1:9000
  RootUser: gabriel
  RootPassword: leirbag123
  UseSSL: false
