server:
  AppVersion: 1.0.0
  Port: :5000
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: secretkey
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false


logger:
  Development: true
  DisableCaller: false
  DisableStracktrace: false
  Enconding: json
  Level: info


postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: gabriel
  PostgresqlPassword: leirbag123
  PostgresqlDbname: database
  PostgresqlSslmode: false
  PgDriver: pgx
