basePath: /api/v1
definitions:
  models.User:
    properties:
      about:
        type: string
      avatar:
        type: string
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      is_email_verified:
        type: boolean
      last_login:
        type: string
      last_name:
        type: string
      password:
        type: string
      role:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  models.UserWithToken:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
info:
  contact:
    name: Gabriel Santos
    url: https://github.com/gabrielopesantos/
  description: Project for educational purposes
  title: myDrive API
  version: 0.0.1
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: register new user, returns user and token
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.UserWithToken'
      summary: Register new user
      tags:
      - Auth
swagger: "2.0"
