name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
  name: tests
  runs-on: ubuntu-latest
  steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.5'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
